### ISSUE TITLE
Versioning in tool

### ISSUE THREAD

**Issue by harivyasi** [mekkyz/ymlio#12]
It might be a good to include `version` as a feature in the tool i.e. implement `ymlio -v` command.

One can then also always include a comment: `# written using ymlio vX.x` in all the files that are written using the tool.

**Comment by mekkyz** [comment]
Added both of the proposed input for versioning and adding a comment while combining.
@harivyasi I also fixed the thing with --only. Should now work probably. You can also `go build -o ymlio` and then use ./ymlio as the rootCmd.
