### ISSUE TITLE
Remove unnecessary empty lines from sources

### ISSUE THREAD

**Issue by ptrxyz** [mekkyz/ymlio#4]
A lot of unnecessary empty lines are present in the source files, i.e.: 

https://github.com/mekkyz/ymlio/blob/d1392e646377e4aa19d9f851db7f284534996f0a/cmd/combinecmd.go#L17
https://github.com/mekkyz/ymlio/blob/d1392e646377e4aa19d9f851db7f284534996f0a/cmd/combinecmd.go#L40
https://github.com/mekkyz/ymlio/blob/d1392e646377e4aa19d9f851db7f284534996f0a/cmd/combinecmd.go#L45
https://github.com/mekkyz/ymlio/blob/d1392e646377e4aa19d9f851db7f284534996f0a/cmd/splityamlcmd.go#L97
https://github.com/mekkyz/ymlio/blob/d1392e646377e4aa19d9f851db7f284534996f0a/cmd/splityamlcmd.go#L150-L155
https://github.com/mekkyz/ymlio/blob/d1392e646377e4aa19d9f851db7f284534996f0a/cmd/splityamlcmd.go#L234
... and others ...

**Comment by mekkyz** [comment]
fixed
