### ISSUE TITLE
combining file appends data if the output file exists

### ISSUE THREAD

**Issue by ptrxyz** [mekkyz/ymlio#8]
If the output file of a combine operation exists, the output file should be overwritten instead of the data being appended.

**Comment by harivyasi** [comment]
Maybe it would be a good idea to add a reverse flag to not overwrite e.g. `ymlio --overwrite-prompt`.

**Comment by mekkyz** [comment]
@Peter -> Fixed. It now overwrite by default
@Shashank -> Great Idea -> Added. Although it now overwrites by default, but with the flag --extend or -e it will append instead of overwrite
